quarkus.http.cors.origins=http://localhost:4200

quarkus.datasource.username=sentinel_user
quarkus.datasource.password=password_super_sicura
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/iotsentinel_db
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.database.generation=update

# Configurazione DAO Sensore: può essere "sql" oppure "memory"
iotsentinel.dao.sensore.strategy=sql
